sonar.projectKey=D-sorder_php-project-48
sonar.organization=d-sorder

sonar.sources=src
sonar.tests=tests
sonar.php.coverage.reportPaths=build/logs/clover.xml
sonar.exclusions=**/vendor/**, **/tests/**
