name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.5'
          tools: composer, phpcs, phpunit

      - name: Install dependencies
        run: make install

      - name: Run linter
        run: make lint

      - name: Run tests with coverage
        run: make test-coverage

      - name: Send coverage to SonarCloud
        uses: SonarSource/sonarcloud-github-action@v2
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          with:
            args: >
              -Dsonar.organization=d-sorder
              -Dsonar.projectKey=D-sorder_php-project-48
              -Dsonar.php.coverage.reportPaths=build/logs/clover.xml
